//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.PowerToys.Run.Plugin.QuickNotes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Community.PowerToys.Run.Plugin.QuickNotes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PluginName => ResourceManager.GetString("PluginName", resourceCulture) ?? "QuickNotes";
        internal static string PluginDescription => ResourceManager.GetString("PluginDescription", resourceCulture) ?? "Save, view, manage, search, tag, and pin quick notes";
        
        // Command Descriptions
        internal static string CommandHelp => ResourceManager.GetString("CommandHelp", resourceCulture) ?? "Show help with available commands ℹ️";
        internal static string CommandBackup => ResourceManager.GetString("CommandBackup", resourceCulture) ?? "Create a backup of notes 💾";
        internal static string CommandExport => ResourceManager.GetString("CommandExport", resourceCulture) ?? "Export notes to a file 💾";
        internal static string CommandEdit => ResourceManager.GetString("CommandEdit", resourceCulture) ?? "Edit note by number 📝";
        internal static string CommandView => ResourceManager.GetString("CommandView", resourceCulture) ?? "View note details 👁️";
        internal static string CommandDelAll => ResourceManager.GetString("CommandDelAll", resourceCulture) ?? "Delete all notes 💣";
        internal static string CommandDel => ResourceManager.GetString("CommandDel", resourceCulture) ?? "Delete note by number 🗑️";
        internal static string CommandSearch => ResourceManager.GetString("CommandSearch", resourceCulture) ?? "Search notes by text 🔍";
        internal static string CommandSearchTag => ResourceManager.GetString("CommandSearchTag", resourceCulture) ?? "Search notes by tag 🏷️";
        internal static string CommandPin => ResourceManager.GetString("CommandPin", resourceCulture) ?? "Pin note to top of list 📌";
        internal static string CommandUnpin => ResourceManager.GetString("CommandUnpin", resourceCulture) ?? "Unpin note 📎";
        internal static string CommandUndo => ResourceManager.GetString("CommandUndo", resourceCulture) ?? "Undo last deletion ↩️";
        internal static string CommandSort => ResourceManager.GetString("CommandSort", resourceCulture) ?? "Sort notes by date or text 🔄";
        internal static string CommandTagStyle => ResourceManager.GetString("CommandTagStyle", resourceCulture) ?? "Change tag display style (bold/italic) ✨";
        internal static string CommandMarkdown => ResourceManager.GetString("CommandMarkdown", resourceCulture) ?? "Create multi-line markdown note 📝";
        internal static string CommandSync => ResourceManager.GetString("CommandSync", resourceCulture) ?? "Sync notes to Git repository ☁️";
        internal static string CommandRestore => ResourceManager.GetString("CommandRestore", resourceCulture) ?? "Restore notes from Git repository ☁️";
        
        // Settings Labels
        internal static string SettingsNotesFolderPath => ResourceManager.GetString("SettingsNotesFolderPath", resourceCulture) ?? "Notes folder path";
        internal static string SettingsNotesFolderPathDesc => ResourceManager.GetString("SettingsNotesFolderPathDesc", resourceCulture) ?? "Leave empty to use the default AppData location. The folder will be created if it does not exist.";
        internal static string SettingsNotesFolderPathPlaceholder => ResourceManager.GetString("SettingsNotesFolderPathPlaceholder", resourceCulture) ?? @"Example: C:\Users\User\Documents\QuickNotes";
        internal static string SettingsEnableGitSync => ResourceManager.GetString("SettingsEnableGitSync", resourceCulture) ?? "Enable Git Sync";
        internal static string SettingsEnableGitSyncDesc => ResourceManager.GetString("SettingsEnableGitSyncDesc", resourceCulture) ?? "Enable automatic synchronization with Git repository";
        internal static string SettingsGitRepositoryUrl => ResourceManager.GetString("SettingsGitRepositoryUrl", resourceCulture) ?? "Git Repository URL";
        internal static string SettingsGitRepositoryUrlDesc => ResourceManager.GetString("SettingsGitRepositoryUrlDesc", resourceCulture) ?? "Example: https://github.com/username/notes.git";
        internal static string SettingsGitBranch => ResourceManager.GetString("SettingsGitBranch", resourceCulture) ?? "Git Branch";
        internal static string SettingsGitBranchDesc => ResourceManager.GetString("SettingsGitBranchDesc", resourceCulture) ?? "Branch name (default: main)";
        internal static string SettingsGitUsername => ResourceManager.GetString("SettingsGitUsername", resourceCulture) ?? "Git Username (optional)";
        internal static string SettingsGitUsernameDesc => ResourceManager.GetString("SettingsGitUsernameDesc", resourceCulture) ?? "Uses global git config if empty";
        internal static string SettingsGitEmail => ResourceManager.GetString("SettingsGitEmail", resourceCulture) ?? "Git Email (optional)";
        internal static string SettingsGitEmailDesc => ResourceManager.GetString("SettingsGitEmailDesc", resourceCulture) ?? "Uses global git config if empty";
        
        // Messages and Titles
        internal static string NotInitialized => ResourceManager.GetString("NotInitialized", resourceCulture) ?? "QuickNotes not initialized";
        internal static string NotInitializedDesc => ResourceManager.GetString("NotInitializedDesc", resourceCulture) ?? "Plugin not initialized properly. Please restart PowerToys.";
        internal static string DuplicateQQDetected => ResourceManager.GetString("DuplicateQQDetected", resourceCulture) ?? "Duplicate 'qq' detected";
        internal static string DuplicateQQDetectedDesc => ResourceManager.GetString("DuplicateQQDetectedDesc", resourceCulture) ?? "Using '{0}' instead. No need to type 'qq' twice.";
        internal static string AddNote => ResourceManager.GetString("AddNote", resourceCulture) ?? "Add note: {0}";
        internal static string AddNoteSubtitle => ResourceManager.GetString("AddNoteSubtitle", resourceCulture) ?? "Press Enter to save this note (with timestamp)";
        internal static string ExecuteCommand => ResourceManager.GetString("ExecuteCommand", resourceCulture) ?? "Execute command '{0}'";
        internal static string NoteSaved => ResourceManager.GetString("NoteSaved", resourceCulture) ?? "Note saved";
        internal static string NoteSavedDesc => ResourceManager.GetString("NoteSavedDesc", resourceCulture) ?? "Saved: {0}";
        internal static string FileInUse => ResourceManager.GetString("FileInUse", resourceCulture) ?? "File in use";
        internal static string FileInUseDesc => ResourceManager.GetString("FileInUseDesc", resourceCulture) ?? "Notes file is used by another process. Please try again shortly.";
        internal static string ErrorCreatingNote => ResourceManager.GetString("ErrorCreatingNote", resourceCulture) ?? "Error creating note";
        
        // Git Sync Messages
        internal static string GitSyncNotEnabled => ResourceManager.GetString("GitSyncNotEnabled", resourceCulture) ?? "⚠️ Git Sync is not enabled";
        internal static string GitSyncNotEnabledSubtitle => ResourceManager.GetString("GitSyncNotEnabledSubtitle", resourceCulture) ?? "Enable it in PowerToys Settings → PowerToys Run → Plugins → QuickNotes";
        internal static string GitSyncDisabled => ResourceManager.GetString("GitSyncDisabled", resourceCulture) ?? "Git Sync Disabled";
        internal static string GitSyncDisabledInstructions => ResourceManager.GetString("GitSyncDisabledInstructions", resourceCulture) ?? "Go to PowerToys Settings → PowerToys Run → Plugins → QuickNotes → Additional Options\n\n1. Check 'Enable Git Sync'\n2. Set your Git Repository URL\n3. Configure branch (default: main)\n4. Optionally set username and email";
        internal static string GitRepoNotConfigured => ResourceManager.GetString("GitRepoNotConfigured", resourceCulture) ?? "⚠️ Git Repository not configured";
        internal static string GitRepoNotConfiguredSubtitle => ResourceManager.GetString("GitRepoNotConfiguredSubtitle", resourceCulture) ?? "Click to see setup instructions";
        internal static string ConfigureGitRepo => ResourceManager.GetString("ConfigureGitRepo", resourceCulture) ?? "Configure Git Repository";
        internal static string ConfigureGitRepoInstructions => ResourceManager.GetString("ConfigureGitRepoInstructions", resourceCulture) ?? "Go to PowerToys Settings → QuickNotes → Additional Options\n\nSet your repository URL:\n• HTTPS: https://github.com/username/notes.git\n• SSH: git@github.com:username/notes.git";
        internal static string GitSyncError => ResourceManager.GetString("GitSyncError", resourceCulture) ?? "❌ Git Sync Error";
        internal static string GitSyncErrorDesc => ResourceManager.GetString("GitSyncErrorDesc", resourceCulture) ?? "Could not initialize Git Sync service.";
        internal static string SyncNotesToGit => ResourceManager.GetString("SyncNotesToGit", resourceCulture) ?? "☁️ Sync notes to Git repository";
        internal static string SyncNotesToGitSubtitle => ResourceManager.GetString("SyncNotesToGitSubtitle", resourceCulture) ?? "Repository: {0} | Branch: {1} | Press Enter to sync";
        internal static string SyncCompleted => ResourceManager.GetString("SyncCompleted", resourceCulture) ?? "✅ Sync Completed";
        internal static string SyncFailed => ResourceManager.GetString("SyncFailed", resourceCulture) ?? "❌ Sync Failed";
        internal static string RestoreFromGit => ResourceManager.GetString("RestoreFromGit", resourceCulture) ?? "⚠️ Restore notes from Git repository?";
        internal static string RestoreFromGitSubtitle => ResourceManager.GetString("RestoreFromGitSubtitle", resourceCulture) ?? "Repository: {0} | Branch: {1} | This will replace your local notes. Press Enter to continue.";
        internal static string RestoreCompleted => ResourceManager.GetString("RestoreCompleted", resourceCulture) ?? "✅ Restore Completed";
        internal static string RestoreFailed => ResourceManager.GetString("RestoreFailed", resourceCulture) ?? "❌ Restore Failed";
        
        // Markdown Editor
        internal static string CreateMarkdownNote => ResourceManager.GetString("CreateMarkdownNote", resourceCulture) ?? "Create Markdown Note";
        internal static string CreateMarkdownNoteSubtitle => ResourceManager.GetString("CreateMarkdownNoteSubtitle", resourceCulture) ?? "Open multi-line editor for markdown notes with live preview";
        internal static string MarkdownNoteSaved => ResourceManager.GetString("MarkdownNoteSaved", resourceCulture) ?? "Markdown Note Saved";
        internal static string MarkdownNoteSavedDesc => ResourceManager.GetString("MarkdownNoteSavedDesc", resourceCulture) ?? "Your multi-line markdown note has been saved successfully!";
        internal static string FailedToOpenMarkdownEditor => ResourceManager.GetString("FailedToOpenMarkdownEditor", resourceCulture) ?? "Failed to open markdown editor: {0}";
        
        // Search
        internal static string SearchQuickNotes => ResourceManager.GetString("SearchQuickNotes", resourceCulture) ?? "Search QuickNotes";
        internal static string SearchUsage => ResourceManager.GetString("SearchUsage", resourceCulture) ?? "Usage: qq search <term>";
        internal static string NoMatchesFound => ResourceManager.GetString("NoMatchesFound", resourceCulture) ?? "No matches found";
        internal static string NoNotesContain => ResourceManager.GetString("NoNotesContain", resourceCulture) ?? "No notes contain '{0}'.";
        internal static string SearchByTag => ResourceManager.GetString("SearchByTag", resourceCulture) ?? "Search by Tag";
        internal static string SearchByTagUsage => ResourceManager.GetString("SearchByTagUsage", resourceCulture) ?? "Usage: qq searchtag <tag> (e.g., qq searchtag work)";
        internal static string NoNotesWithTag => ResourceManager.GetString("NoNotesWithTag", resourceCulture) ?? "No notes found with tag '{0}'.";
        internal static string FoundNoteWithTag => ResourceManager.GetString("FoundNoteWithTag", resourceCulture) ?? "Found note with tag '{0}'. Enter to copy.";
        
        // Tag Style
        internal static string TagStyleSetToBold => ResourceManager.GetString("TagStyleSetToBold", resourceCulture) ?? "Tag style set to bold";
        internal static string TagStyleBoldDesc => ResourceManager.GetString("TagStyleBoldDesc", resourceCulture) ?? "Tags will now appear as 【#tag】";
        internal static string TagStyleSetToItalic => ResourceManager.GetString("TagStyleSetToItalic", resourceCulture) ?? "Tag style set to italic";
        internal static string TagStyleItalicDesc => ResourceManager.GetString("TagStyleItalicDesc", resourceCulture) ?? "Tags will now appear as 〈#tag〉";
        internal static string InvalidTagStyle => ResourceManager.GetString("InvalidTagStyle", resourceCulture) ?? "Invalid tag style";
        internal static string InvalidTagStyleDesc => ResourceManager.GetString("InvalidTagStyleDesc", resourceCulture) ?? "Use 'qq tagstyle bold' or 'qq tagstyle italic'";
        
        // Notes Display
        internal static string PinnedNotes => ResourceManager.GetString("PinnedNotes", resourceCulture) ?? "--- Pinned Notes ---";
        internal static string Notes => ResourceManager.GetString("Notes", resourceCulture) ?? "--- Notes ---";
        internal static string PinnedNoteSubtitle => ResourceManager.GetString("PinnedNoteSubtitle", resourceCulture) ?? "Pinned | Enter to copy clean content (no timestamp/tags) | Ctrl+Click to Edit | qq unpin {0}";
        internal static string NoteSubtitle => ResourceManager.GetString("NoteSubtitle", resourceCulture) ?? "Press Enter to copy without timestamp | Ctrl+C for full note | Ctrl+Click to Edit";
        internal static string SearchNoteSubtitle => ResourceManager.GetString("SearchNoteSubtitle", resourceCulture) ?? "Press Enter to copy | Shift+Enter for content only | Ctrl+Click to Edit";
        internal static string NoNotesFound => ResourceManager.GetString("NoNotesFound", resourceCulture) ?? "No notes found";
        internal static string NoNotesFoundDesc => ResourceManager.GetString("NoNotesFoundDesc", resourceCulture) ?? "Type 'qq <your note>' to add one, or 'qq help' for commands.";
        internal static string NoNotesMatch => ResourceManager.GetString("NoNotesMatch", resourceCulture) ?? "No notes match '{0}'";
        internal static string NoNotesMatchDesc => ResourceManager.GetString("NoNotesMatchDesc", resourceCulture) ?? "Try a different search or add a new note.";
        internal static string NoteDetails => ResourceManager.GetString("NoteDetails", resourceCulture) ?? "Note Details";
        internal static string NoteDetailsTooltip => ResourceManager.GetString("NoteDetailsTooltip", resourceCulture) ?? "ID: {0}\nDisplay Index: {1}\nPinned: {2}\nCreated: {3}\nText: {4}\n\nTip: Right-click for copy options or edit.";
        
        // Delete
        internal static string ConfirmDeletion => ResourceManager.GetString("ConfirmDeletion", resourceCulture) ?? "Confirm Deletion";
        internal static string ConfirmDeleteNote => ResourceManager.GetString("ConfirmDeleteNote", resourceCulture) ?? "Delete note #{0}?\n{1}\nPress Enter to confirm";
        internal static string Cancel => ResourceManager.GetString("Cancel", resourceCulture) ?? "Cancel";
        internal static string KeepThisNote => ResourceManager.GetString("KeepThisNote", resourceCulture) ?? "Keep this note";
        internal static string NoteNotFound => ResourceManager.GetString("NoteNotFound", resourceCulture) ?? "Note not found";
        internal static string NoteNotFoundDesc => ResourceManager.GetString("NoteNotFoundDesc", resourceCulture) ?? "Note number {0} does not exist.\nAvailable: {1}";
        internal static string MultipleMatchingNotes => ResourceManager.GetString("MultipleMatchingNotes", resourceCulture) ?? "Multiple matching notes found";
        internal static string MultiplePartialMatchingNotes => ResourceManager.GetString("MultiplePartialMatchingNotes", resourceCulture) ?? "Multiple partial matching notes found";
        internal static string SelectNoteToDelete => ResourceManager.GetString("SelectNoteToDelete", resourceCulture) ?? "Please select a specific note to delete:";
        internal static string DeleteNoteNumber => ResourceManager.GetString("DeleteNoteNumber", resourceCulture) ?? "Delete #{0}: {1}";
        internal static string PinnedPressEnterToDelete => ResourceManager.GetString("PinnedPressEnterToDelete", resourceCulture) ?? "[PINNED] Press Enter to delete";
        internal static string PressEnterToDelete => ResourceManager.GetString("PressEnterToDelete", resourceCulture) ?? "Press Enter to delete";
        internal static string NoteNotFoundByContent => ResourceManager.GetString("NoteNotFoundByContent", resourceCulture) ?? "No note with content '{0}' was found. Try using the note number instead.";
        internal static string NoteNotFoundInFile => ResourceManager.GetString("NoteNotFoundInFile", resourceCulture) ?? "The note was not found in the file. It may have been deleted already.";
        internal static string NoteDeleted => ResourceManager.GetString("NoteDeleted", resourceCulture) ?? "Note deleted";
        internal static string NoteDeletedDesc => ResourceManager.GetString("NoteDeletedDesc", resourceCulture) ?? "Removed note #{0}: {1}\nTip: Use 'qq undo' to restore the note.";
        internal static string ErrorDeletingNote => ResourceManager.GetString("ErrorDeletingNote", resourceCulture) ?? "Error deleting note";
        internal static string ErrorDeletingNoteDesc => ResourceManager.GetString("ErrorDeletingNoteDesc", resourceCulture) ?? "Could not delete note: {0}\nPlease try again or restart PowerToys Run.";
        
        // Pin/Unpin
        internal static string NotePinned => ResourceManager.GetString("NotePinned", resourceCulture) ?? "Note pinned";
        internal static string NoteUnpinned => ResourceManager.GetString("NoteUnpinned", resourceCulture) ?? "Note unpinned";
        internal static string ErrorPinningNote => ResourceManager.GetString("ErrorPinningNote", resourceCulture) ?? "Error pinning note";
        internal static string ErrorUnpinningNote => ResourceManager.GetString("ErrorUnpinningNote", resourceCulture) ?? "Error unpinning note";
        
        // Sort
        internal static string NoNotesToSort => ResourceManager.GetString("NoNotesToSort", resourceCulture) ?? "No notes to sort";
        internal static string InvalidSortType => ResourceManager.GetString("InvalidSortType", resourceCulture) ?? "Invalid sort type";
        internal static string InvalidSortTypeDesc => ResourceManager.GetString("InvalidSortTypeDesc", resourceCulture) ?? "Use 'qq sort date [asc|desc]' or 'qq sort alpha [asc|desc]'";
        internal static string NotesSorted => ResourceManager.GetString("NotesSorted", resourceCulture) ?? "Notes sorted";
        internal static string NotesSortedDesc => ResourceManager.GetString("NotesSortedDesc", resourceCulture) ?? "Sorted by {0} {1}";
        internal static string ErrorSortingNotes => ResourceManager.GetString("ErrorSortingNotes", resourceCulture) ?? "Error sorting notes";
        
        // Edit
        internal static string EditNoteNumber => ResourceManager.GetString("EditNoteNumber", resourceCulture) ?? "Edit note #{0}";
        internal static string EditNoteSubtitle => ResourceManager.GetString("EditNoteSubtitle", resourceCulture) ?? "Press Enter to edit: {0}";
        internal static string EditQuickNote => ResourceManager.GetString("EditQuickNote", resourceCulture) ?? "Edit QuickNote";
        internal static string ErrorSavingEditedNote => ResourceManager.GetString("ErrorSavingEditedNote", resourceCulture) ?? "Error saving edited note";
        internal static string CouldNotFindNoteInFile => ResourceManager.GetString("CouldNotFindNoteInFile", resourceCulture) ?? "Could not find the note in the file.";
        internal static string CouldNotFindNoteToSaveEdit => ResourceManager.GetString("CouldNotFindNoteToSaveEdit", resourceCulture) ?? "Could not find note to save edit. Refresh and retry.";
        internal static string ErrorSavingNote => ResourceManager.GetString("ErrorSavingNote", resourceCulture) ?? "Error saving note";
        
        // View
        internal static string ViewNoteSubtitle => ResourceManager.GetString("ViewNoteSubtitle", resourceCulture) ?? "Press Enter to copy without timestamp | Ctrl+C for full note | Right-click for options";
        
        // Backup/Export
        internal static string NoNotesFileToBackup => ResourceManager.GetString("NoNotesFileToBackup", resourceCulture) ?? "No notes file to backup";
        internal static string NotesFileDoesntExist => ResourceManager.GetString("NotesFileDoesntExist", resourceCulture) ?? "The notes file doesn't exist.";
        internal static string BackupCreated => ResourceManager.GetString("BackupCreated", resourceCulture) ?? "Backup created";
        internal static string BackupCreatedDesc => ResourceManager.GetString("BackupCreatedDesc", resourceCulture) ?? "Backup saved to: {0}\nBackup folder opened.";
        internal static string ErrorCreatingBackup => ResourceManager.GetString("ErrorCreatingBackup", resourceCulture) ?? "Error creating backup";
        internal static string NoNotesFileToExport => ResourceManager.GetString("NoNotesFileToExport", resourceCulture) ?? "No notes file to export";
        internal static string NoNotesToExport => ResourceManager.GetString("NoNotesToExport", resourceCulture) ?? "No notes to export";
        internal static string NotesFileEmpty => ResourceManager.GetString("NotesFileEmpty", resourceCulture) ?? "Your notes file is empty.";
        internal static string ExportCreated => ResourceManager.GetString("ExportCreated", resourceCulture) ?? "Export created";
        internal static string ExportCreatedDesc => ResourceManager.GetString("ExportCreatedDesc", resourceCulture) ?? "Export saved to: {0}\nExport folder opened.";
        internal static string ErrorCreatingExport => ResourceManager.GetString("ErrorCreatingExport", resourceCulture) ?? "Error creating export";
        
        // Help
        internal static string QuickNotesHelp => ResourceManager.GetString("QuickNotesHelp", resourceCulture) ?? "QuickNotes Help";
        internal static string HelpText => ResourceManager.GetString("HelpText", resourceCulture) ?? "qq <text>              Add note ✏️       | qq pin <N>             Pin note 📌\nqq search <text>        Search notes 🔍      | qq searchtag <tag>     Search by tag\nqq view <N>              View note         | qq sort <field> <dir>  Sort notes\nqq edit <N> <new text>   Edit note ✏️      | qq pin/unpin <N>     Pin/unpin note 📌\nqq del <N>             Delete note 🗑️    | qq backup/export       Backup/Export notes 💾\nqq delall              Delete all notes    | qq undo                Undo last delete\nqq tagstyle <style>    hash/fancy style";
        
        // Delete All
        internal static string ConfirmDeleteAll => ResourceManager.GetString("ConfirmDeleteAll", resourceCulture) ?? "Confirm deletion of ALL notes";
        internal static string ConfirmDeleteAllDesc => ResourceManager.GetString("ConfirmDeleteAllDesc", resourceCulture) ?? "This will permanently delete all {0} notes. Are you sure?";
        internal static string KeepYourNotes => ResourceManager.GetString("KeepYourNotes", resourceCulture) ?? "Keep your notes (no changes made)";
        internal static string AllNotesDeleted => ResourceManager.GetString("AllNotesDeleted", resourceCulture) ?? "All notes deleted";
        internal static string AllNotesDeletedDesc => ResourceManager.GetString("AllNotesDeletedDesc", resourceCulture) ?? "All notes have been permanently deleted. You can find a backup in the same folder.";
        internal static string NoNotesToDelete => ResourceManager.GetString("NoNotesToDelete", resourceCulture) ?? "No notes to delete";
        internal static string NotesFileAlreadyEmpty => ResourceManager.GetString("NotesFileAlreadyEmpty", resourceCulture) ?? "Your notes file is already empty.";
        internal static string ErrorDeletingAllNotes => ResourceManager.GetString("ErrorDeletingAllNotes", resourceCulture) ?? "Error deleting all notes";
        
        // Undo
        internal static string NothingToUndo => ResourceManager.GetString("NothingToUndo", resourceCulture) ?? "Nothing to undo";
        internal static string NothingToUndoDesc => ResourceManager.GetString("NothingToUndoDesc", resourceCulture) ?? "No recently deleted note. Delete one first.";
        internal static string NoteRestored => ResourceManager.GetString("NoteRestored", resourceCulture) ?? "Note restored";
        internal static string NoteRestoredDesc => ResourceManager.GetString("NoteRestoredDesc", resourceCulture) ?? "Restored note{0}.\n{1}";
        internal static string ErrorRestoringNote => ResourceManager.GetString("ErrorRestoringNote", resourceCulture) ?? "Error restoring note";
        
        // Validation
        internal static string InvalidNoteNumber => ResourceManager.GetString("InvalidNoteNumber", resourceCulture) ?? "Invalid note number";
        internal static string InvalidNoteNumberDesc => ResourceManager.GetString("InvalidNoteNumberDesc", resourceCulture) ?? "Specify a valid positive number. E.g. 'qq del 3'";
        internal static string NoNotesToOperate => ResourceManager.GetString("NoNotesToOperate", resourceCulture) ?? "No notes to operate on. Add a note first.";
        internal static string NoteNumberDoesNotExist => ResourceManager.GetString("NoteNumberDoesNotExist", resourceCulture) ?? "Note #{0} does not exist. Highest is {1}.\nAvailable: {2}";
        internal static string NoteDoesNotExist => ResourceManager.GetString("NoteDoesNotExist", resourceCulture) ?? "Note #{0} does not exist. Available: {1}";
        
        // Context Menu
        internal static string CopyFullNote => ResourceManager.GetString("CopyFullNote", resourceCulture) ?? "Copy Full Note (with timestamp)";
        internal static string CopyCleanContent => ResourceManager.GetString("CopyCleanContent", resourceCulture) ?? "Copy Clean Content (no timestamp, no tags)";
        internal static string EditNote => ResourceManager.GetString("EditNote", resourceCulture) ?? "Edit Note...";
        internal static string DeleteNote => ResourceManager.GetString("DeleteNote", resourceCulture) ?? "Delete Note";
        internal static string PinNote => ResourceManager.GetString("PinNote", resourceCulture) ?? "Pin Note";
        internal static string UnpinNote => ResourceManager.GetString("UnpinNote", resourceCulture) ?? "Unpin Note";
        internal static string OpenUrl => ResourceManager.GetString("OpenUrl", resourceCulture) ?? "Open URL: {0}";
        internal static string FailedToCopy => ResourceManager.GetString("FailedToCopy", resourceCulture) ?? "Failed to copy: {0}";
        internal static string CouldNotOpenUrl => ResourceManager.GetString("CouldNotOpenUrl", resourceCulture) ?? "Could not open URL: {0}";
        internal static string FailedToCopyNote => ResourceManager.GetString("FailedToCopyNote", resourceCulture) ?? "Failed to copy note: {0}";
        internal static string Error => ResourceManager.GetString("Error", resourceCulture) ?? "Error";
        internal static string ErrorReadingNotes => ResourceManager.GetString("ErrorReadingNotes", resourceCulture) ?? "Error reading notes";
        internal static string ErrorWritingNotes => ResourceManager.GetString("ErrorWritingNotes", resourceCulture) ?? "Error writing notes";
        
        // Markdown Dialog
        internal static string MarkdownEditorTitle => ResourceManager.GetString("MarkdownEditorTitle", resourceCulture) ?? "QuickNotes - Markdown Editor";
        internal static string MarkdownInput => ResourceManager.GetString("MarkdownInput", resourceCulture) ?? "Markdown Input:";
        internal static string Preview => ResourceManager.GetString("Preview", resourceCulture) ?? "Preview:";
        internal static string PreviewPlaceholder => ResourceManager.GetString("PreviewPlaceholder", resourceCulture) ?? "Preview will appear here...";
        internal static string MarkdownSyntaxHelp => ResourceManager.GetString("MarkdownSyntaxHelp", resourceCulture) ?? "Markdown Syntax Help";
        internal static string SaveNote => ResourceManager.GetString("SaveNote", resourceCulture) ?? "Save Note (Ctrl+Enter)";
        internal static string CancelEsc => ResourceManager.GetString("CancelEsc", resourceCulture) ?? "Cancel (Esc)";
        internal static string EmptyNote => ResourceManager.GetString("EmptyNote", resourceCulture) ?? "Empty Note";
        internal static string PleaseEnterText => ResourceManager.GetString("PleaseEnterText", resourceCulture) ?? "Please enter some text for your note.";
        internal static string MarkdownEditorInstructions => ResourceManager.GetString("MarkdownEditorInstructions", resourceCulture) ?? "Use markdown syntax for formatting. Press Ctrl+Enter to save, Escape to cancel.";
        
        // Misc
        internal static string Unknown => ResourceManager.GetString("Unknown", resourceCulture) ?? "Unknown";
        internal static string Descending => ResourceManager.GetString("Descending", resourceCulture) ?? "descending";
        internal static string Ascending => ResourceManager.GetString("Ascending", resourceCulture) ?? "ascending";
        internal static string DefaultAsc => ResourceManager.GetString("DefaultAsc", resourceCulture) ?? "(default asc)";
        internal static string NowNoteNumber => ResourceManager.GetString("NowNoteNumber", resourceCulture) ?? " (now note #{0})";
        internal static string Details => ResourceManager.GetString("Details", resourceCulture) ?? "Details:";
    }
}
