name: Build and Release QuickNotes

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'

# Permissions for GITHUB_TOKEN (principle of least privilege)
permissions:
  contents: write  # Needed for creating releases
  issues: read
  pull-requests: read

# Add restrictions for parallel runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x64, arm64]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: Build
        run: dotnet build QuickNotes/QuickNotes.sln -c Release -p:Platform="${{ matrix.platform }}"
      
      - name: Get version
        id: get_version
        shell: bash
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            # Remove 'v' prefix for package naming convention
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
            echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            echo "IS_TAG=true" >> $GITHUB_OUTPUT
          else
            echo "VERSION=$(date +'%Y.%m.%d')-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT
            echo "TAG_VERSION=v$(date +'%Y.%m.%d')-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT
            echo "IS_TAG=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Debug Output
        run: |
          Get-ChildItem -Path "QuickNotes" -Recurse -Directory | Where-Object { $_.Name -eq "Release" } | ForEach-Object { Write-Host $_.FullName }
        shell: pwsh
      
      - name: Create output directory
        run: mkdir -p artifacts
      
      - name: Copy build output to artifacts directory
        run: |
          # Use VERSION without 'v' prefix for directory naming
          $artifactDir = "artifacts/QuickNotes-${{ steps.get_version.outputs.VERSION }}-${{ matrix.platform }}"
          
          # Create the artifact directory
          New-Item -ItemType Directory -Force -Path $artifactDir
          
          # Create QuickNotes subfolder
          New-Item -ItemType Directory -Force -Path "$artifactDir/QuickNotes"
          
          # Define the direct path to the build output
          $buildOutput = "QuickNotes/Community.PowerToys.Run.Plugin.QuickNotes/bin/${{ matrix.platform }}/Release"
          
          Write-Host "Using build output directory: $buildOutput"
          
          # Check if the directory exists
          if (-not (Test-Path $buildOutput)) {
            Write-Host "Build output directory not found at expected path. Searching for it..."
            $buildOutput = Get-ChildItem -Path "QuickNotes" -Recurse -Directory | 
                           Where-Object { $_.Name -eq "Release" -and $_.FullName -like "*${{ matrix.platform }}*" } | 
                           Select-Object -First 1 -ExpandProperty FullName
            
            if ($buildOutput) {
              Write-Host "Found build output directory: $buildOutput"
            } else {
              Write-Error "Could not find any Release directory for platform ${{ matrix.platform }}"
              exit 1
            }
          }
          
          # Check if build output exists before proceeding
          if (-not (Test-Path $buildOutput)) {
            Write-Error "Build output directory not found"
            exit 1
          }
          
          # Check for files directly in the build output directory
          $files = Get-ChildItem -Path $buildOutput -File
          if ($files.Count -gt 0) {
            Write-Host "Found $($files.Count) files in build output directory. Copying directly..."
            Copy-Item -Path "$buildOutput/*" -Destination "$artifactDir/QuickNotes" -Recurse -Force
            Write-Host "Files copied successfully"
          } else {
            # Look for a .NET runtime folder
            $runtimeFolder = Get-ChildItem -Path $buildOutput -Directory | 
                             Where-Object { $_.Name -like "net*-windows*" } | 
                             Select-Object -First 1 -ExpandProperty FullName
            
            if ($runtimeFolder) {
              Write-Host "Found runtime folder: $runtimeFolder"
              Copy-Item -Path "$runtimeFolder/*" -Destination "$artifactDir/QuickNotes" -Recurse -Force
              Write-Host "Files copied successfully from runtime folder"
            } else {
              # If no runtime folder, check for any subdirectories
              $subDirs = Get-ChildItem -Path $buildOutput -Directory
              if ($subDirs.Count -gt 0) {
                $firstSubDir = $subDirs[0].FullName
                Write-Host "No runtime folder found, but found subdirectory: $firstSubDir"
                Copy-Item -Path "$firstSubDir/*" -Destination "$artifactDir/QuickNotes" -Recurse -Force
                Write-Host "Files copied from first subdirectory"
              } else {
                Write-Error "No files or subdirectories found in build output directory"
                exit 1
              }
            }
          }
        shell: pwsh
      
      - name: Create ZIP archive
        run: |
          # Use VERSION without 'v' prefix for ZIP naming (PowerToys convention)
          $artifactDir = "artifacts/QuickNotes-${{ steps.get_version.outputs.VERSION }}-${{ matrix.platform }}"
          # Ensure correct naming convention without 'v' prefix
          $zipFile = "QuickNotes-${{ steps.get_version.outputs.VERSION }}-${{ matrix.platform }}.zip"
          
          # Create the zip file
          Compress-Archive -Path "$artifactDir/QuickNotes" -DestinationPath "artifacts/$zipFile"
          
          Write-Host "Created ZIP file: $zipFile"
        shell: pwsh
      
      - name: Generate checksums
        run: |
          # Generate SHA256 checksums for PowerToys Run plugin validation
          $zipFile = "QuickNotes-${{ steps.get_version.outputs.VERSION }}-${{ matrix.platform }}.zip"
          $zipPath = "artifacts/$zipFile"
          $hashFile = "artifacts/$zipFile.sha256"
          
          if (Test-Path $zipPath) {
            $hash = (Get-FileHash -Path $zipPath -Algorithm SHA256).Hash
            $hash | Out-File -FilePath $hashFile -Encoding ASCII -NoNewline
            Write-Host "Generated checksum for $zipFile`: $hash"
          } else {
            Write-Error "ZIP file not found: $zipPath"
            exit 1
          }
        shell: pwsh
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.platform }}
          path: |
            artifacts/*.zip
            artifacts/*.sha256
  
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Get version from tag
        id: get_version
        run: |
          # Remove 'v' prefix for package naming
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Prepare Release Notes
        id: release_notes
        run: |
          cat > release_notes.md << 'EOL'
          # 📝 QuickNotes v${{ steps.get_version.outputs.VERSION }}
          
          ![QuickNotes Logo](https://raw.githubusercontent.com/ruslanlap/CommunityPowerToysRunPlugin-QuickNotes/master/QuickNotes/Community.PowerToys.Run.Plugin.QuickNotes/Images/quicknotes.dark.png)
          
          ## ✨ What's New
          
          <!-- Add your release highlights here -->
          - 🚀 Performance improvements
          - 🐛 Bug fixes
          - ✨ New features
          
          ## 📥 Installation
          
          1. Download the ZIP file for your platform (x64 or ARM64)
          2. Extract to `%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins\`
          3. Restart PowerToys
          4. Start using with `Alt+Space` then type `qq`
          
          ## 🔍 Quick Commands
          
          | Command | Description |
          |---------|-------------|
          | `qq <text>` | Create a new note |
          | `qq help` | Show help information |
          | `qq search <word>` | Search notes |
          | `qq edit <number>` | Edit a specific note |
          | `qq view <number>` | View note details |
          | `qq backup` | Backup notes |
          
          ## 📦 Package Files
          
          - `QuickNotes-${{ steps.get_version.outputs.VERSION }}-x64.zip` - For x64 systems
          - `QuickNotes-${{ steps.get_version.outputs.VERSION }}-arm64.zip` - For ARM64 systems
          - `.sha256` files contain checksums for verification
          
          ## 🙏 Thank You
          
          Thank you for using QuickNotes! If you encounter any issues or have suggestions, please [open an issue](https://github.com/ruslanlap/CommunityPowerToysRunPlugin-QuickNotes/issues).
          
          Made with ❤️ by <a href="https://github.com/ruslanlap">ruslanlap</a>
          EOL
          
          RELEASE_NOTES=$(cat release_notes.md)
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_OUTPUT
          echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: QuickNotes v${{ steps.get_version.outputs.VERSION }}
          body: ${{ steps.release_notes.outputs.RELEASE_NOTES }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            artifacts/build-artifacts-x64/*.zip
            artifacts/build-artifacts-x64/*.sha256
            artifacts/build-artifacts-arm64/*.zip
            artifacts/build-artifacts-arm64/*.sha256
            
      - name: Create Latest Release Artifacts
        if: success()
        run: |
          mkdir -p latest_release
          # Copy with proper naming convention (no 'v' prefix)
          cp artifacts/build-artifacts-x64/QuickNotes-${{ steps.get_version.outputs.VERSION }}-x64.zip latest_release/QuickNotes-latest-x64.zip
          cp artifacts/build-artifacts-arm64/QuickNotes-${{ steps.get_version.outputs.VERSION }}-arm64.zip latest_release/QuickNotes-latest-arm64.zip
      
      - name: Update Latest Release Artifacts
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          name: QuickNotes v${{ steps.get_version.outputs.VERSION }}
          tag_name: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            latest_release/QuickNotes-latest-x64.zip
            latest_release/QuickNotes-latest-arm64.zip