name: Build and Release QuickNotes

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'

# Permissions for GITHUB_TOKEN (principle of least privilege)
permissions:
  contents: write  # Needed for creating releases
  issues: read
  pull-requests: read

# Add restrictions for parallel runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x64, arm64]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: Build
        run: dotnet build QuickNotes/QuickNotes.sln -c Release -p:Platform="${{ matrix.platform }}"
      
      - name: Get version
        id: get_version
        shell: bash
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
            echo "IS_TAG=true" >> $GITHUB_OUTPUT
          else
            echo "VERSION=$(date +'%Y.%m.%d')-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT
            echo "IS_TAG=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Debug Output
        run: |
          Get-ChildItem -Path "QuickNotes" -Recurse -Directory | Where-Object { $_.Name -eq "Release" } | ForEach-Object { Write-Host $_.FullName }
        shell: pwsh
      
      - name: Create output directory
        run: mkdir -p artifacts
      
      - name: Copy build output to artifacts directory
        run: |
          $artifactDir = "artifacts/QuickNotes-v${{ steps.get_version.outputs.VERSION }}-${{ matrix.platform }}"
          
          # Create the artifact directory
          New-Item -ItemType Directory -Force -Path $artifactDir
          
          # Create QuickNotes subfolder
          New-Item -ItemType Directory -Force -Path "$artifactDir/QuickNotes"
          
          # Find the build output directory
          $buildOutput = Get-ChildItem -Path "QuickNotes" -Recurse -Directory | 
                         Where-Object { $_.Name -eq "Release" -and $_.FullName -like "*${{ matrix.platform }}*" } | 
                         Select-Object -First 1 -ExpandProperty FullName
          
          Write-Host "Found build output directory: $buildOutput"
          
          # Find the .NET runtime folder (net9.0-windows10.0.22621.0) inside the build output
          $runtimeFolder = Get-ChildItem -Path $buildOutput -Directory | 
                           Where-Object { $_.Name -like "net*-windows*" } | 
                           Select-Object -First 1 -ExpandProperty FullName
          
          Write-Host "Found runtime folder: $runtimeFolder"
          
          # Copy all files from the runtime folder directly to the QuickNotes subfolder
          if (Test-Path $runtimeFolder) {
            Copy-Item -Path "$runtimeFolder/*" -Destination "$artifactDir/QuickNotes" -Recurse
            Write-Host "Files copied successfully"
          } else {
            Write-Error "Runtime folder not found"
            exit 1
          }
        shell: pwsh
      
      - name: Create ZIP archive
        run: |
          $artifactDir = "artifacts/QuickNotes-v${{ steps.get_version.outputs.VERSION }}-${{ matrix.platform }}"
          $zipFile = "QuickNotes-v${{ steps.get_version.outputs.VERSION }}-${{ matrix.platform }}.zip"
          
          # Create the zip file
          Compress-Archive -Path "$artifactDir/QuickNotes" -DestinationPath "artifacts/$zipFile"
        shell: pwsh
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.platform }}
          path: artifacts/*.zip
  
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Prepare Release Notes
        id: release_notes
        run: |
          cat > release_notes.md << 'EOL'
          # 📝 QuickNotes v${{ steps.get_version.outputs.VERSION }}
          
          ![QuickNotes Logo](https://raw.githubusercontent.com/ruslanlap/CommunityPowerToysRunPlugin-QuickNotes/main/QuickNotes/Community.PowerToys.Run.Plugin.QuickNotes/Images/quicknotes.dark.png)
          
          ## ✨ What's New
          
          <!-- Add your release highlights here -->
          - 🚀 Performance improvements
          - 🐛 Bug fixes
          - ✨ New features
          
          ## 📥 Installation
          
          1. Download the ZIP file for your platform (x64 or ARM64)
          2. Extract to `%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins\`
          3. Restart PowerToys
          4. Start using with `Alt+Space` then type `qq`
          
          ## 🔍 Quick Commands
          
          | Command | Description |
          |---------|-------------|
          | `qq <text>` | Create a new note |
          | `qq help` | Show help information |
          | `qq search <word>` | Search notes |
          | `qq edit <number>` | Edit a specific note |
          | `qq view <number>` | View note details |
          | `qq backup` | Backup notes |
          
          ## 🙏 Thank You
          
          Thank you for using QuickNotes! If you encounter any issues or have suggestions, please [open an issue](https://github.com/ruslanlap/CommunityPowerToysRunPlugin-QuickNotes/issues).
          
          Made with ❤️ by the community
          EOL
          
          RELEASE_NOTES=$(cat release_notes.md)
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_OUTPUT
          echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: QuickNotes v${{ steps.get_version.outputs.VERSION }}
          body: ${{ steps.release_notes.outputs.RELEASE_NOTES }}
          draft: false
          prerelease: false
          files: |
            artifacts/build-artifacts-x64/*.zip
            artifacts/build-artifacts-arm64/*.zip
            
      - name: Create Latest Release Artifacts
        if: success()
        run: |
          mkdir -p latest_release
          cp artifacts/build-artifacts-x64/QuickNotes-v${{ steps.get_version.outputs.VERSION }}-x64.zip latest_release/QuickNotes-latest-x64.zip
          cp artifacts/build-artifacts-arm64/QuickNotes-v${{ steps.get_version.outputs.VERSION }}-arm64.zip latest_release/QuickNotes-latest-arm64.zip
      
      - name: Update Latest Release Artifacts
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          name: QuickNotes v${{ steps.get_version.outputs.VERSION }}
          tag_name: latest
          files: |
            latest_release/QuickNotes-latest-x64.zip
            latest_release/QuickNotes-latest-arm64.zip
